# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   This function accepts an array of filenames and strips the filename from each.
#from the resulting array.
#
#
#
Puppet::Functions.create_function(:'classroom::dirnames') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

  unless args[0].is_a?(Array)
    raise Puppet::ParseError, "dirnames(): expected an Array, got #{args[0].inspect}"
  end

  args[0].collect do |file|
    File.dirname(file)
  end

  end
end
